name: emolens_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.0
  youtube_player_flutter: ^9.1.1

  table_calendar: ^3.0.9
  fl_chart: ^0.66.0

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5
  audioplayers: ^5.2.1
  google_fonts: ^8.0.2
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  url_launcher: ^6.3.0
  pdfx: ^2.9.0
  flutter_timezone: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/emolens_logo_terbaru.jpeg"

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/image/mood.png
    - assets/image/streak.png
    - assets/image/pojok_cerita.png
    - assets/image/backgournd_dashboard_cewe/
    - assets/image/backgournd_dashboard_cewe/backgournd_dashboard_cewe.png
    - assets/image/backgournd_dashboard_cewe/11.png
    - assets/image/backgournd_dashboard_cewe/22.png
    - assets/image/backgournd_dashboard_cewe/33.png
    - assets/image/backgournd_dashboard_cewe/44.png
    - assets/image/backgournd_dashboard_cewe/55.png
    - assets/image/backgournd_dashboard_cewe/mood.png
    - assets/image/backgournd_dashboard_cewe/pojok_cerita.png
    - assets/image/backgournd_dashboard_cewe/streak.png
   