import 'dart:math';

class QuoteData {
  static final Map<String, List<String>> moodQuotes = {
    'senang': [
      'Nikmati setiap momen yang membuat senyumanmu bertambah.',
      'Kebahagiaan adalah pilihan, dan kamu memilihnya hari ini.',
      'Pancarkan energi positifmu ke seluruh dunia.',
      'Senyummu adalah cahaya bagi orang-orang di sekitarmu.',
      'Rayakan kemenangan kecil yang kamu raih hari ini.',
      'Dunia terasa lebih indah saat hatimu penuh syukur.',
      'Lanjutkan langkahmu dengan penuh kegembiraan.',
      'Kamu pantas mendapatkan semua kebahagiaan ini.',
      'Simpan memori indah ini di tempat spesial dalam hatimu.',
      'Kebahagiaanmu menular, terima kasih telah menjadi dirimu.',
      'Teruslah bersinar, dunia butuh lebih banyak cahaya sepertimu.',
      'Hari ini adalah bukti bahwa hal-hal baik sedang terjadi.',
      'Jangan lupa berbagi tawa dengan seseorang hari ini.',
      'Hatimu adalah taman, dan hari ini bunga-bunga bermekaran.',
      'Biarkan kebahagiaan ini menjadi bahan bakarmu untuk besok.',
      
      
      'Setiap tawa adalah doa yang terjawab.',
      'Keajaiban terjadi pada mereka yang percaya dan bahagia.',
      'Jadikan hari ini alasan untuk mencintai hidup lebih dalam.',
      'Kamu adalah arsitek kebahagiaanmu sendiri.',
      'Tertawalah selagi bisa, itu adalah obat terbaik.',
      'Keindahan hidup terpancar dari hati yang senang.',
      'Fokus pada hal-hal yang membuat jiwamu bernyanyi.',
      'Terima kasih pada diri sendiri karena telah bertahan hingga saat bahagia ini.',
      'Biarkan duniamu dihiasi oleh warna-warna ceria.',
      'Langkahmu terasa ringan saat hatimu bebas dari beban.',
      'Kesenangan sederhana seringkali adalah yang paling berharga.',
      'Bagikan secercah harapan melalui senyum manismu.',
      'Hari yang cerah dimulai dari pikiran yang positif.',
      'Kamu adalah inspirasi bagi mereka yang mencari kebahagiaan.',
      'Jangan biarkan apapun memadamkan api kegembiraanmu.',
      'Hidup adalah petualangan yang menyenangkan jika kamu mengizinkannya.',
      'Temukan keajaiban dalam hal-hal biasa hari ini.',
      'Jadilah alasan seseorang tersenyum hari ini.',
      'Kebahagiaan sejati ditemukan dalam memberi dan berbagi.',
      'Masa depanmu secerah impian yang kamu yakini.',
      'Syukuri napasmu, syukuri detak jantungmu, syukuri hari ini.',
      'Kamu luar biasa, dan dunia mengakuinya.',
      'Biarkan hatimu menari mengikuti irama syukur.',
      'Tidak ada batasan untuk apa yang bisa kamu capai dengan hati yang senang.',
      'Energi positifmu adalah magnet bagi hal-hal baik.',
      'Jadilah versi terbaik dirimu yang penuh suka cita.',
      'Kebahagiaan bukan tujuan, tapi cara kita berjalan.',
      'Hargai dirimu karena telah sampai di titik ini.',
      'Setiap momen adalah peluang untuk merasa bahagia.',
      'Pilihlah untuk melihat sisi terang dalam setiap situasi.',
      'Hatimu tahu jalan menuju kedamaian dan kegembiraan.',
      'Semesta mendukung setiap langkah bahagiamu.',
      'Percayalah bahwa hari esok akan membawa lebih banyak tawa.',
      'Kamu adalah berkah bagi dunia ini.',
      'Nikmati prosesmu, karena di sanalah kebahagiaan berada.',
    ],
    'sedih': [
      'Ada kekuatan dalam memberi dirimu waktu untuk merasakan dan sembuh.',
      'Air mata adalah cara hati berbicara ketika mulut tak sanggup lagi.',
      'Awan mendung akan berlalu, dan matahari akan bersinar kembali.',
      'Jangan terburu-buru, sembuh butuh waktu yang tidak sebentar.',
      'Kamu tidak sendirian dalam perasaan ini.',
      'Peluk dirimu sendiri, kamu telah berjuang sangat keras.',
      'Bahkan di hari tergelap, masih ada benih harapan di dalam dirimu.',
      'Merasa lelah itu manusiawi, istirahatlah sejenak.',
      'Esok adalah halaman baru yang belum tertulis.',
      'Kesedihan ini hanyalah musim yang sedang berganti.',
      'Bicaralah pada seseorang, beban akan terasa lebih ringan.',
      'Setiap luka akan meninggalkan pelajaran yang berharga.',
      'Jangan biarkan kegelapan hari ini menutupi cahaya hari esok.',
      'Kamu lebih kuat dari yang kamu bayangkan saat ini.',
      'Biarkan dirimu menangis, itu adalah proses pembersihan jiwa.',
      'Keheningan kadang memberikan jawaban yang paling tenang.',
      'Satu langkah kecil tetaplah sebuah kemajuan.',
      'Hargai setiap tetes air mata sebagai bukti empati dirimu.',
      'Kamu berhak merasa begini, jangan tekan perasaanmu.',
      'Kedamaian akan datang kembali ke dalam hatimu.',
      'Fokuslah pada pernapasanmu, satu per satu.',
      'Malam yang paling gelap menghasilkan bintang yang paling terang.',
      'Kamu dicintai lebih dari yang kamu sadari.',
      'Jangan menyerah pada hari yang sulit ini.',
      'Bunga membutuhkan hujan untuk tumbuh, begitu juga jiwamu.',
      'Temukan kenyamanan dalam hal-hal kecil di sekitarmu.',
      'Kesedihan adalah jembatan menuju pemahaman yang lebih dalam.',
      'Jadilah lembut pada dirimu sendiri hari ini.',
      'Setiap akhir adalah awal dari sesuatu yang baru.',
      'Keberanian tidak selalu berteriak, kadang ia adalah suara tenang di akhir hari.',
      'Kamu punya ruang untuk tumbuh dari rasa sakit ini.',
      'Jangan bandingkan proses sembuhmu dengan orang lain.',
      'Cahaya akan selalu menemukan jalannya menembus celah terkecil.',
      'Ingatlah masa-masa sulit yang pernah kamu lalui dan menangkan.',
      'Hatimu akan belajar untuk tertawa kembali, percayalah.',
      'Kesabaran adalah kunci untuk melewati badai ini.',
      'Dunia tidak akan berhenti berputar karena kamu sedang sedih.',
      'Ambil waktu sebanyak yang kamu butuhkan.',
      'Harapan adalah jangkar yang menjaga jiwamu tetap stabil.',
      'Kamu berharga, apa pun yang kamu rasakan saat ini.',
      'Jangan biarkan satu bab buruk mengakhiri seluruh ceritamu.',
      'Kesedihan mengajarimu arti dari kebahagiaan sejati.',
      'Biarkan musik atau seni menjadi pelipur laramu.',
      'Tuhan tidak akan membebani hamba-Nya di luar kemampuannya.',
      'Ada keindahan dalam kerapuhan yang kamu tunjukkan.',
      'Percayalah bahwa segalanya akan membaik pada waktunya.',
      'Kamu adalah pejuang yang sedang beristirahat sejenak.',
      'Jangan lupa untuk bernapas dalam-dalam.',
      'Jiwamu sedang bertumbuh melalui pengalaman ini.',
      'Hari yang cerah sedang menantimu di ujung jalan ini.',
    ],
    'marah': [
      'Tarik napas panjang, lalu biarkan emosi itu menjadi tenaga yang lebih baik.',
      'Kemarahan adalah emosi yang valid, tapi jangan biarkan ia mengendalikanmu.',
      'Hitung sampai sepuluh sebelum kamu bereaksi.',
      'Kedamaian lebih berharga daripada memenangkan argumen.',
      'Gunakan energimu untuk membangun, bukan untuk merusak.',
      'Lepaskan apa yang tidak bisa kamu kendalikan.',
      'Kemarahan yang tertahan seperti memegang bara api.',
      'Maafkan bukan karena mereka pantas, tapi karena kamu pantas damai.',
      'Biarkan logikamu memimpin saat emosimu sedang membara.',
      'Kamu lebih besar dari situasi yang membuatmu marah ini.',
      'Jangan biarkan kemarahan orang lain mencuri ketenanganmu.',
      'Gunakan suaramu untuk kebenaran, bukan untuk kebencian.',
      'Setiap detik kamu marah, kamu kehilangan enam puluh detik kebahagiaan.',
      'Pilihlah untuk menjadi bijak daripada menjadi benar.',
      'Terkadang diam adalah respon yang paling kuat.',
      'Salurkan emosimu melalui aktivitas fisik atau kreativitas.',
      'Hargai dirimu dengan tidak membiarkan amarah merusak harimu.',
      'Pahami akar dari kemarahanmu untuk menemukan solusinya.',
      'Kemarahan adalah pertanda bahwa ada sesuatu yang perlu diperbaiki.',
      'Bersikaplah asertif tanpa harus menjadi agresif.',
      'Ingatlah bahwa setiap orang sedang berjuang dengan beban masing-masing.',
      'Kendalikan reaksimu, itulah kekuatan sejatimu.',
      'Kemarahan adalah kabut yang menutupi kejernihan berpikir.',
      'Jangan ambil keputusan saat hatimu sedang panas.',
      'Berikan dirimu ruang untuk menenangkan diri.',
      'Kebaikan adalah penawar yang paling ampuh untuk kebencian.',
      'Fokus pada solusi daripada menyalahkan keadaan.',
      'Kamu punya kekuatan untuk mengubah konflik menjadi diskusi.',
      'Hargai batasanmu dan komunikasikan dengan tenang.',
      'Kemarahan seringkali adalah topeng dari rasa takut atau sedih.',
      'Jadilah pelindung bagi ketenangan batinmu sendiri.',
      'Lepaskan dendam agar langkahmu terasa lebih ringan.',
      'Dunia butuh lebih banyak empati dan sedikit amarah.',
      'Setiap kali kamu tenang menghadapi badai, kamu tumbuh.',
      'Jangan biarkan api amarah membakar jembatan yang telah kamu bangun.',
      'Belajarlah untuk melepaskan hal-hal yang menyakitimu.',
      'Kedewasaan adalah kemampuan untuk tetap tenang di bawah tekanan.',
      'Jadilah contoh bagaimana menangani emosi dengan dewasa.',
      'Kemarahan tidak akan pernah menyelesaikan masalah jangka panjang.',
      'Pilihlah kata-katamu dengan hati-hati saat sedang emosi.',
      'Tarik napas, hembuskan, lepaskan.',
      'Kamu berhak mendapatkan lingkungan yang damai.',
      'Jangan biarkan satu momen buruk merusak hubungan yang berharga.',
      'Fokuslah pada apa yang benar-benar penting bagi hidupmu.',
      'Ambil kendali atas pikiranmu sendiri hari ini.',
      'Kemarahan adalah ujian bagi karaktermu.',
      'Tunjukkan kekuatanmu melalui penguasaan diri.',
      'Kedamaian batin adalah pencapaian tertinggi.',
      'Jangan biarkan dunia mengubah kelembutan hatimu.',
      'Kembalilah ke pusat ketenanganmu.',
    ],
    'takut': [
      'Ketakutan hanyalah pintu menuju keberanian yang belum kamu temui.',
      'Ketakutan adalah reaksi, keberanian adalah keputusan.',
      'Lakukan saja meski kamu merasa takut.',
      'Ketakutanmu tidak sebesar kekuatan yang ada di dalam dirimu.',
      'Bernapaslah, kamu aman di saat ini.',
      'Setiap ketakutan yang kamu hadapi akan membuatmu lebih kuat.',
      'Ketakutan hanyalah imajinasi yang digunakan dengan cara yang salah.',
      'Percayalah pada kemampuanmu untuk melewati ini.',
      'Dunia ini penuh dengan peluang, jangan biarkan takut menghalangimu.',
      'Satu langkah berani akan mengubah segalanya.',
      'Hadapi ketakutanmu, dan ia akan kehilangan kekuatannya.',
      'Kamu dilindungi dan dijaga oleh kekuatan yang lebih besar.',
      'Ketakutan adalah pengingat bahwa kamu sedang keluar dari zona nyaman.',
      'Fokuslah pada cahaya, bukan pada bayang-bayang.',
      'Kamu punya semua yang dibutuhkan untuk menghadapi tantangan ini.',
      'Jangan biarkan "bagaimana jika" menghentikan "apa yang bisa".',
      'Keberanian adalah melakukan apa yang kamu takuti.',
      'Ingatlah kesuksesan yang pernah kamu raih di masa lalu.',
      'Ketakutan hanyalah perasaan, ia bukan kenyataan.',
      'Ambil napas dalam dan rasakan kekuatan dalam dirimu.',
      'Semesta selalu mendukung langkah-langkah beranimu.',
      'Ketakutan akan luntur saat kamu mulai melangkah.',
      'Jadikan ketakutan sebagai guru, bukan sebagai tuan.',
      'Kamu lebih tangguh dari apa pun yang menakutimu.',
      'Percayalah pada proses kehidupan.',
      'Ketakutan hanyalah awan yang lewat di langit pikiranmu.',
      'Fokus pada hal kecil yang bisa kamu kendalikan saat ini.',
      'Keberanian tumbuh setiap kali kamu berkata "ya" pada tantangan.',
      'Jangan biarkan rasa takut mencuri mimpimu.',
      'Kamu tidak sendirian, mintalah bantuan jika perlu.',
      'Hadapi hari ini dengan kepala tegak.',
      'Ketakutan adalah tanda bahwa kamu peduli pada masa depanmu.',
      'Gunakan rasa takut sebagai energi untuk waspada, bukan untuk berhenti.',
      'Langkah pertama selalu yang paling sulit, tapi yang paling penting.',
      'Kamu berhak merasa aman dan tenang.',
      'Visualisasikan kesuksesanmu di balik ketakutan itu.',
      'Ingatkan dirimu tentang betapa jauhnya kamu telah melangkah.',
      'Ketakutan seringkali lebih besar di pikiran daripada di kenyataan.',
      'Jadilah pahlawan dalam ceritamu sendiri hari ini.',
      'Jangan biarkan kegagalan yang belum terjadi menghentikanmu.',
      'Ketakutan akan hilang saat kamu bertindak.',
      'Pikiran yang tenang adalah senjata terbaik melawan rasa takut.',
      'Kamu dicintai dan didukung oleh orang-orang di sekitarmu.',
      'Percayalah bahwa segalanya akan bekerja untuk kebaikanmu.',
      'Ketakutan adalah jembatan menuju pertumbuhan diri.',
      'Hadapi rintangan itu dengan keyakinan penuh.',
      'Kamu adalah pemenang sejak lahir.',
      'Biarkan keberanianmu menjadi kompas dalam kegelapan.',
      'Ketakutan hanyalah ujian kecil bagi imanmu.',
      'Langkahkan kakimu dengan percaya diri hari ini.',
    ],
    'biasa': [
      'Hari-hari tenang adalah fondasi yang kuat untuk emosi positif berikutnya.',
      'Nikmati ketenangan yang ada di sekitarmu saat ini.',
      'Rutinitas adalah irama yang menjaga hidup tetap teratur.',
      'Kebahagiaan seringkali ditemukan dalam kesederhanaan.',
      'Hargai momen damai ini sebelum badai atau pelangi datang.',
      'Kamu sedang berada di titik keseimbangan yang baik.',
      'Gunakan waktu tenang ini untuk refleksi diri.',
      'Kesederhanaan adalah bentuk kemewahan yang paling tinggi.',
      'Hari yang biasa adalah berkah yang sering terlupakan.',
      'Biarkan pikiranmu beristirahat dalam keadaan netral ini.',
      'Tidak perlu selalu ada drama untuk merasa hidup.',
      'Kedamaian batin dimulai dari menerima hal-hal apa adanya.',
      'Fokuslah pada kehadiranmu di sini dan saat ini.',
      'Hari yang tenang adalah waktu terbaik untuk merencanakan masa depan.',
      'Syukuri setiap detik napas yang mengalir tanpa hambatan.',
      'Keindahan ada dalam hal-hal kecil yang terlihat biasa saja.',
      'Jadilah pengamat yang bijak atas duniamu sendiri.',
      'Titik nol adalah tempat yang baik untuk memulai hal baru.',
      'Keseimbangan adalah kunci menuju kesehatan mental yang baik.',
      'Nikmati secangkir minuman hangat dan kedamaian hati.',
      'Hari ini adalah kanvas kosong yang menanti sentuhanmu.',
      'Kebahagiaan tidak selalu harus meledak-ledak.',
      'Hargai dirimu karena mampu tetap stabil.',
      'Dunia terasa lebih jernih saat emosimu tenang.',
      'Gunakan energi yang stabil ini untuk menyelesaikan tugasmu.',
      'Momen biasa seringkali menjadi kenangan yang paling dirindukan.',
      'Kedamaian bukan berarti tidak ada kebisingan, tapi ketenangan di tengahnya.',
      'Jadilah jangkar bagi dirimu sendiri hari ini.',
      'Pikiran yang netral adalah pikiran yang terbuka.',
      'Syukuri bahwa hari ini berjalan sesuai rencana.',
      'Kehidupan yang tenang adalah hadiah bagi jiwa yang lelah.',
      'Jangan remehkan kekuatan dari hari yang damai.',
      'Setiap hari adalah kesempatan untuk belajar hal baru, meski biasa saja.',
      'Kamu sedang membangun pondasi untuk kesuksesan masa depan.',
      'Hargai ritme alami hidupmu.',
      'Ketenangan adalah bentuk kekuatan yang tersembunyi.',
      'Jangan mencari kegembiraan di luar, temukan kedamaian di dalam.',
      'Hari yang biasa adalah bukti bahwa hidupmu stabil.',
      'Gunakan waktu ini untuk terhubung kembali dengan dirimu.',
      'Kebahagiaan adalah merasa cukup dengan apa yang ada.',
      'Percayalah bahwa setiap momen memiliki tujuannya sendiri.',
      'Jadilah versi dirimu yang paling tenang hari ini.',
      'Dunia tidak butuh pahlawan setiap hari, kadang ia hanya butuh kehadiranmu.',
      'Keseimbangan emosi adalah fondasi kebahagiaan jangka panjang.',
      'Syukuri ketenangan ini sebagai bentuk cinta semesta padamu.',
      'Fokus pada hal-hal yang benar-benar penting bagimu.',
      'Hari yang biasa adalah waktu yang tepat untuk berbuat baik secara diam-diam.',
      'Kehidupan yang seimbang adalah kehidupan yang indah.',
      'Biarkan hatimu merasa puas dengan hari yang tenang ini.',
      'Lanjutkan langkahmu dengan kestabilan dan keyakinan.',
    ],
    'terkejut': [
      'Biarkan kejutan itu mengajarkanmu bahwa hidup tetap penuh warna.',
      'Hal yang tak terduga seringkali membawa pelajaran terbaik.',
      'Terimalah kejutan ini dengan rasa ingin tahu yang besar.',
      'Hidup selalu punya cara untuk mengejutkan kita.',
      'Jadikan momen ini sebagai pembuka mata bagi peluang baru.',
      'Ketidakterdugaan adalah bumbu yang membuat hidup menarik.',
      'Reaksimu terhadap kejutan menentukan jalannya harimu.',
      'Tetaplah fleksibel menghadapi perubahan yang tiba-tiba.',
      'Ada keindahan dalam ketidakpastian yang mengejutkan.',
      'Gunakan kejutan ini untuk keluar dari rutinitasmu.',
      'Setiap kejutan adalah pesan tersembunyi dari semesta.',
      'Jangan takut pada hal yang tak terduga, hadapi dengan berani.',
      'Kejutan mengingatkan kita bahwa kita tidak mengendalikan segalanya.',
      'Temukan hikmah di balik peristiwa yang mengejutkanmu ini.',
      'Keajaiban seringkali datang dalam bentuk kejutan yang tak disangka.',
      'Biarkan dirimu terpesona oleh misteri kehidupan.',
      'Kejutan adalah cara hidup mengajak kita untuk bangun.',
      'Hadapi setiap kejutan dengan pikiran terbuka.',
      'Perubahan mendadak bisa menjadi awal dari kesuksesan besar.',
      'Syukuri kejutan yang membawamu ke arah yang lebih baik.',
      'Ingatlah bahwa kejutan buruk sekalipun bisa berakhir baik.',
      'Kejutan menguji seberapa cepat kita bisa beradaptasi.',
      'Jangan biarkan kejutan membuatmu kehilangan keseimbangan.',
      'Tarik napas dan cerna apa yang baru saja terjadi.',
      'Kejutan adalah bukti bahwa hidup masih penuh dengan rahasia.',
      'Pilihlah untuk melihat sisi positif dari setiap kejutan.',
      'Momen terkejut adalah saat di mana kita paling merasa hidup.',
      'Jadikan kejutan ini sebagai motivasi untuk terus maju.',
      'Hidup adalah petualangan yang tak terduga, nikmatilah.',
      'Setiap tikungan jalan membawa kejutan yang berbeda.',
      'Kejutan bisa menjadi jawaban atas doa yang kamu lupakan.',
      'Hargai spontanitas yang dibawa oleh kejutan ini.',
      'Dunia sedang mencoba memberitahumu sesuatu yang penting.',
      'Kejutan adalah percikan yang menyalakan kreativitas.',
      'Tetaplah tenang meski situasinya berubah seketika.',
      'Kejutan mengingatkan kita untuk selalu siap sedia.',
      'Jangan biarkan rasa terkejut berubah menjadi rasa takut.',
      'Ada kekuatan dalam ketidakpastian yang mengejutkan.',
      'Gunakan momen ini untuk belajar tentang dirimu sendiri.',
      'Kejutan adalah hadiah yang dibungkus dengan ketidakterdugaan.',
      'Percayalah bahwa semesta tahu apa yang dia lakukan.',
      'Jadilah fleksibel seperti air menghadapi rintangan baru.',
      'Kejutan membuat kita tetap rendah hati dan waspada.',
      'Syukuri kejutan yang membuat harimu menjadi lebih berwarna.',
      'Setiap kejutan memiliki cerita yang layak diceritakan.',
      'Jangan remehkan dampak dari perubahan kecil yang tiba-tiba.',
      'Kejutan adalah cara alam menjaga keseimbangan.',
      'Tetaplah optimis meski dikejutkan oleh tantangan.',
      'Kejutan adalah pintu menuju pemahaman yang lebih luas.',
      'Nikmati perjalanan yang penuh dengan kejutan ini.',
    ],
    'jijik': [
      'Emosi ini memberi tahu bahwa kamu peduli pada kesejahteraanmu, hargai itu.',
      'Jijik adalah sinyal alami untuk melindungi kesehatan dan integritasmu.',
      'Gunakan perasaan ini untuk menetapkan batasan yang lebih sehat.',
      'Hargai nalurimu untuk menjauhi hal-hal yang tidak baik bagimu.',
      'Kebersihan batin sama pentingnya dengan kebersihan fisik.',
      'Pilihlah lingkungan yang membuatmu merasa nyaman dan bersih.',
      'Rasa jijik mengingatkan kita akan standar kualitas hidup kita.',
      'Jangan biarkan hal-hal yang negatif merusak kesucian pikiranmu.',
      'Fokuslah pada hal-hal yang murni dan membangun jiwa.',
      'Hormati perasaanmu dan bertindaklah untuk melindungi dirimu.',
      'Rasa jijik adalah pelindung yang membantu kita tetap aman.',
      'Gunakan emosi ini sebagai motivasi untuk melakukan perbaikan.',
      'Kamu berhak atas ruang yang bersih dan energi yang positif.',
      'Jangan paksa dirimu untuk menerima hal yang melanggar nilai-harimu.',
      'Kebersihan adalah sebagian dari iman dan ketenangan.',
      'Pahami apa yang memicu perasaan ini untuk menghindarinya di masa depan.',
      'Rasa jijik adalah cara tubuh berkata "ini bukan untukku".',
      'Fokus pada pembersihan diri dan lingkunganmu hari ini.',
      'Hargai integritasmu dengan menjauhi pengaruh yang merusak.',
      'Jadilah pemilih dalam hal-hal yang masuk ke dalam pikiranmu.',
      'Rasa jijik mengajarkan kita arti dari kesucian dan keindahan.',
      'Ciptakan zona nyaman yang bebas dari hal-hal yang mengganggu.',
      'Kembalikan fokusmu pada hal-hal yang membuatmu merasa segar.',
      'Rasa jijik adalah filter alami yang menjaga kualitas hidupmu.',
      'Hormati reaksi alamimu tanpa harus menjadi menghakimi.',
      'Gunakan energi ini untuk membersihkan apa yang perlu dibersihkan.',
      'Kamu punya kontrol atas apa yang kamu izinkan berada di sekitarmu.',
      'Rasa jijik adalah pengingat untuk selalu menjaga keasrian jiwa.',
      'Fokuslah pada keindahan yang ada di dunia ini.',
      'Jangan biarkan rasa jijik berubah menjadi kebencian yang berkepanjangan.',
      'Belajarlah untuk melepaskan hal-hal yang membuatmu merasa tidak nyaman.',
      'Kebersihan pikiran membawa kejernihan bertindak.',
      'Rasa jijik adalah bukti bahwa kamu memiliki standar yang tinggi.',
      'Hargai dirimu dengan tidak berkompromi pada hal-hal yang buruk.',
      'Ciptakan harmoni dengan menjauhi ketidakselarasan.',
      'Rasa jijik adalah bagian dari sistem pertahanan diri yang cerdas.',
      'Fokus pada hal-hal yang menenangkan dan menyejukkan hati.',
      'Gunakan emosi ini untuk memperkuat prinsip hidupmu.',
      'Kamu berhak mendapatkan yang terbaik dan terbersih.',
      'Rasa jijik mengingatkan kita untuk menghargai kesehatan.',
      'Bersihkan energimu setelah berinteraksi dengan hal yang tidak menyenangkan.',
      'Jadilah pelindung bagi kesucian hatimu sendiri.',
      'Rasa jijik adalah sinyal untuk melakukan perubahan positif.',
      'Fokus pada aroma dan pemandangan yang menyegarkan jiwa.',
      'Hargai keunikan sistem emosimu dalam menjaga dirimu.',
      'Jangan biarkan hal-hal yang menjijikkan mencuri kedamaianmu.',
      'Gunakan rasa jijik sebagai kompas untuk mencari kualitas.',
      'Pikiran yang bersih adalah rumah bagi ide-ide cemerlang.',
      'Syukuri nalurimu yang tajam dalam mendeteksi ketidakbaikan.',
      'Kembalilah ke kondisi yang membuatmu merasa murni dan kuat.',
    ],
  };

  static final Map<String, List<Map<String, dynamic>>> dailyInspirations = {
    'Sangat Baik': [
      {'text': 'Pertahankan momentum positifmu. Kebaikan yang kamu tanam hari ini akan berbuah manis esok.', 'icon': '🌟'},
      {'text': 'Bagikan energi bahagiamu pada orang lain. Satu kata baik darimu bisa mengubah hari seseorang.', 'icon': '❤️'},
      {'text': 'Hari ini adalah waktu yang tepat untuk memulai proyek baru yang selama ini kamu impikan.', 'icon': '🚀'},
      {'text': 'Syukuri setiap detail kecil keberhasilanmu. Kamu telah bekerja keras untuk sampai di sini.', 'icon': '🏆'},
      {'text': 'Jadilah cahaya bagi mereka yang sedang mencari jalan. Inspirasimu sangat berarti.', 'icon': '💡'},
      {'text': 'Kondisi mentalmu yang prima adalah aset terbesar. Jaga dengan istirahat yang cukup.', 'icon': '🛡️'},
      {'text': 'Lakukan sesuatu yang menantang hari ini. Kamu sedang dalam kondisi terbaik untuk menang.', 'icon': '🎯'},
      {'text': 'Senyummu adalah doa yang terpancar. Teruslah menebar kebaikan di sekelilingmu.', 'icon': '✨'},
      {'text': 'Rayakan dirimu sendiri. Kamu layak mendapatkan semua apresiasi atas pencapaianmu.', 'icon': '🎊'},
      {'text': 'Gunakan semangatmu untuk menginspirasi perubahan positif di lingkungan sekitarmu.', 'icon': '🌍'},
      {'text': 'Wujudkan impianmu dengan penuh percaya diri hari ini.', 'icon': '🌟'},
      {'text': 'Keberuntungan mengikuti mereka yang berani melangkah dengan bahagia.', 'icon': '🍀'},
      {'text': 'Jadikan setiap detik hari ini sebagai perayaan atas kehidupanmu.', 'icon': '🎈'},
      {'text': 'Kamu adalah magnet bagi segala hal yang indah dan baik.', 'icon': '🧲'},
      {'text': 'Teruslah bermimpi besar, semesta sedang berkonspirasi membantumu.', 'icon': '🌌'},
      {'text': 'Kecerdasan emosionalmu hari ini sangat tinggi, gunakan untuk memimpin.', 'icon': '🧠'},
      {'text': 'Nikmati harmoni antara pikiran, tubuh, dan jiwamu.', 'icon': '🧘'},
      {'text': 'Keberanianmu adalah inspirasi bagi banyak orang di sekitarmu.', 'icon': '🦁'},
      {'text': 'Ciptakan karya yang mencerminkan kegembiraan hatimu.', 'icon': '🎨'},
      {'text': 'Hari ini adalah hari terbaik untuk berbagi kasih sayang.', 'icon': '🫂'},
      {'text': 'Energi positifmu adalah obat bagi mereka yang sedang lelah.', 'icon': '💊'},
      {'text': 'Fokuslah pada visi masa depanmu yang cerah.', 'icon': '🔭'},
      {'text': 'Kamu punya kekuatan untuk mengubah dunia mulai dari dirimu sendiri.', 'icon': '✊'},
      {'text': 'Keindahan hari ini adalah cerminan dari keindahan hatimu.', 'icon': '🌸'},
      {'text': 'Lakukan hal yang membuatmu merasa paling hidup hari ini.', 'icon': '🔥'},
      {'text': 'Jadilah alasan seseorang percaya pada kebaikan manusia lagi.', 'icon': '🤝'},
      {'text': 'Sukses adalah perjalanan, dan kamu sedang menikmati pemandangannya.', 'icon': '🛤️'},
      {'text': 'Hargai setiap hembusan napas sebagai berkah yang luar biasa.', 'icon': '🌬️'},
      {'text': 'Terbukalah pada petualangan baru yang datang menyapamu.', 'icon': '🗺️'},
      {'text': 'Kamu adalah bintang utama dalam panggung kehidupanmu.', 'icon': '🎭'},
      {'text': 'Gunakan kreativitasmu untuk memecahkan masalah dengan cara baru.', 'icon': '💡'},
      {'text': 'Jadilah pemenang yang rendah hati dan penuh empati.', 'icon': '🥇'},
      {'text': 'Kekuatan pikiran positifmu tidak ada batasnya.', 'icon': '♾️'},
      {'text': 'Waktu adalah temanmu, gunakan setiap detiknya dengan bijak dan senang.', 'icon': '⏰'},
      {'text': 'Syukuri kesehatanmu, itu adalah kekayaan yang paling hakiki.', 'icon': '🍎'},
      {'text': 'Biarkan tawamu menjadi musik yang paling merdu hari ini.', 'icon': '🎶'},
      {'text': 'Kamu telah melampaui ekspektasimu sendiri, selamat!', 'icon': '👏'},
      {'text': 'Keberanianmu menghadapi hari ini patut diacungi jempol.', 'icon': '👍'},
      {'text': 'Jadilah pelopor dalam menyebarkan kebahagiaan.', 'icon': '🚩'},
      {'text': 'Duniamu sedang dipenuhi oleh peluang-peluang emas.', 'icon': '💰'},
      {'text': 'Hargai koneksi yang kamu jalin dengan orang-orang tercinta.', 'icon': '🔗'},
      {'text': 'Berikan yang terbaik, dan semesta akan membalasnya dengan lebih baik.', 'icon': '🔄'},
      {'text': 'Fokus pada solusi, bukan pada hambatan.', 'icon': '🧩'},
      {'text': 'Kamu adalah perwujudan dari ketangguhan dan kegembiraan.', 'icon': '💎'},
      {'text': 'Nikmati kebebasan untuk menjadi dirimu yang sejati.', 'icon': '🕊️'},
      {'text': 'Setiap tantangan adalah batu loncatan menuju level baru.', 'icon': '🪜'},
      {'text': 'Jadikan hari ini sebagai mahakarya dalam hidupmu.', 'icon': '🏛️'},
      {'text': 'Kepercayaan dirimu adalah kunci pembuka pintu kesuksesan.', 'icon': '🔑'},
      {'text': 'Biarkan cahaya batinmu menuntun setiap langkahmu.', 'icon': '🕯️'},
      {'text': 'Kamu adalah anugerah bagi setiap orang yang kamu temui.', 'icon': '🎁'},
    ],
    'Stabil': [
      {'text': 'Keseimbangan adalah kunci kedamaian. Teruslah menjaga ritme harianmu dengan bijak.', 'icon': '⚖️'},
      {'text': 'Gunakan waktu tenang ini untuk belajar keterampilan baru atau membaca buku inspiratif.', 'icon': '📚'},
      {'text': 'Konsistensi adalah jalan menuju keahlian. Tetaplah melangkah meski dengan langkah kecil.', 'icon': '🐢'},
      {'text': 'Kedamaian batin adalah hasil dari pikiran yang teratur. Syukuri kestabilan emosimu.', 'icon': '🧘'},
      {'text': 'Jadilah jangkar bagi orang-orang di sekitarmu yang sedang menghadapi badai.', 'icon': '⚓'},
      {'text': 'Fokus pada kesehatan fisikmu hari ini. Jalan santai di sore hari akan sangat membantu.', 'icon': '🚶'},
      {'text': 'Hargai rutinitasmu, karena di sanalah karaktermu dibentuk secara perlahan.', 'icon': '🛠️'},
      {'text': 'Hari yang tenang adalah peluang emas untuk refleksi diri dan perencanaan masa depan.', 'icon': '📝'},
      {'text': 'Keberhasilan bukan hanya tentang lonjakan besar, tapi tentang tetap bertahan di jalur.', 'icon': '🛤️'},
      {'text': 'Ciptakan lingkungan yang mendukung produktivitas dan ketenangan pikiranmu.', 'icon': '🏡'},
      {'text': 'Lakukan hobi yang membuatmu merasa rileks dan terpenuhi.', 'icon': '🎨'},
      {'text': 'Hargai momen saat ini tanpa harus mengkhawatirkan masa depan.', 'icon': '⏳'},
      {'text': 'Jadilah pendengar yang baik bagi dirimu sendiri hari ini.', 'icon': '👂'},
      {'text': 'Kerapian lingkunganmu mencerminkan kerapian pikiranmu.', 'icon': '🧹'},
      {'text': 'Satu perbuatan baik kecil bisa berdampak besar bagi sekitarmu.', 'icon': '🌱'},
      {'text': 'Kesehatan adalah investasi terbaik untuk masa depanmu.', 'icon': '🏥'},
      {'text': 'Gunakan energi stabilmu untuk merapikan hal-hal yang tertunda.', 'icon': '📂'},
      {'text': 'Kejernihan pikiran adalah hasil dari penerimaan diri.', 'icon': '💎'},
      {'text': 'Jangan biarkan kebisingan dunia luar mengganggu ketenangan batinmu.', 'icon': '🔇'},
      {'text': 'Hargai waktu luangmu dengan benar-benar beristirahat.', 'icon': '🛌'},
      {'text': 'Fokus pada kemajuan berkelanjutan, bukan kesempurnaan instan.', 'icon': '📈'},
      {'text': 'Pikiran yang tenang mampu melihat peluang di tengah kesulitan.', 'icon': '👓'},
      {'text': 'Jadilah pilar kekuatan bagi keluargamu hari ini.', 'icon': '🏛️'},
      {'text': 'Sederhanakan hidupmu untuk memperbesar kedamaianmu.', 'icon': '🎋'},
      {'text': 'Belajarlah untuk berkata "tidak" pada hal yang menguras energimu.', 'icon': '🙅'},
      {'text': 'Waktu yang kamu habiskan untuk diri sendiri bukanlah kesia-siaan.', 'icon': '💆'},
      {'text': 'Percayalah pada intuisimu yang sedang jernih saat ini.', 'icon': '🔮'},
      {'text': 'Jadilah pribadi yang tenang menghadapi segala situasi.', 'icon': '🌊'},
      {'text': 'Kekuatan sejati ada dalam pengendalian diri yang baik.', 'icon': '✊'},
      {'text': 'Hargai setiap proses yang kamu lalui dengan sabar.', 'icon': '⏳'},
      {'text': 'Keindahan hidup ada dalam keselarasan antara pikiran dan tindakan.', 'icon': '🧩'},
      {'text': 'Gunakan waktu ini untuk memperkuat hubungan dengan orang tersayang.', 'icon': '💬'},
      {'text': 'Jadilah inspirasi melalui ketenangan dan kestabilanmu.', 'icon': '🕯️'},
      {'text': 'Fokus pada hal-hal esensial yang membawa kebahagiaan jangka panjang.', 'icon': '🎯'},
      {'text': 'Kesehatan mental dimulai dari menghargai batasan diri.', 'icon': '🚧'},
      {'text': 'Jangan terburu-buru, nikmati setiap langkah perjalananmu.', 'icon': '👞'},
      {'text': 'Syukuri hal-hal biasa yang sering luput dari perhatian.', 'icon': '👓'},
      {'text': 'Pikiran yang stabil adalah landasan bagi kreativitas yang sehat.', 'icon': '🏗️'},
      {'text': 'Jadilah teman terbaik bagi dirimu sendiri hari ini.', 'icon': '👫'},
      {'text': 'Kedamaian adalah pilihan yang kamu buat setiap saat.', 'icon': '🕊️'},
      {'text': 'Fokuslah pada rasa cukup dan rasa syukur.', 'icon': '🙏'},
      {'text': 'Kehidupan yang teratur memberikan ruang bagi pertumbuhan jiwa.', 'icon': '🌱'},
      {'text': 'Hargai keheningan sebagai teman dalam merenung.', 'icon': '🤫'},
      {'text': 'Gunakan energimu untuk hal-hal yang memberi dampak positif.', 'icon': '⚡'},
      {'text': 'Ketenanganmu adalah kekuatan yang tak terlihat namun terasa.', 'icon': '🛡️'},
      {'text': 'Jangan biarkan hal sepele merusak hari yang stabil ini.', 'icon': '🧿'},
      {'text': 'Jadilah pribadi yang asertif dan penuh pengertian.', 'icon': '🤝'},
      {'text': 'Setiap detik dalam kondisi stabil adalah kemenangan kecil.', 'icon': '🏁'},
      {'text': 'Percayalah bahwa kamu berada di tempat yang tepat saat ini.', 'icon': '📍'},
      {'text': 'Teruslah bertumbuh dengan cara yang tenang dan pasti.', 'icon': '🌳'},
    ],
    'Waspada': [
      {'text': 'Dengarkan sinyal dari tubuhmu. Jika terasa lelah, berikan dirimu izin untuk beristirahat.', 'icon': '⚠️'},
      {'text': 'Fokus pada satu hal kecil yang bisa kamu kendalikan. Jangan biarkan beban menumpuk.', 'icon': '🔍'},
      {'text': 'Bicaralah pada teman terpercaya. Berbagi cerita bisa mengurangi tekanan yang kamu rasakan.', 'icon': '🗣️'},
      {'text': 'Hindari membuat keputusan besar saat pikiranmu sedang terasa penuh dan berat.', 'icon': '🛑'},
      {'text': 'Lakukan teknik pernapasan dalam untuk menenangkan sistem sarafmu hari ini.', 'icon': '🌬️'},
      {'text': 'Batasi asupan informasi yang memicu kecemasan. Berikan dirimu detoks digital sejenak.', 'icon': '📵'},
      {'text': 'Ingatlah bahwa setiap tantangan memiliki jalan keluar. Tetaplah tenang dan berpikir jernih.', 'icon': '💡'},
      {'text': 'Jadilah lembut pada dirimu sendiri. Kamu tidak harus sempurna setiap saat.', 'icon': '☁️'},
      {'text': 'Fokus pada nutrisi dan hidrasi yang baik untuk mendukung stamina mentalmu.', 'icon': '🍏'},
      {'text': 'Cari aktivitas yang menenangkan seperti mendengarkan musik atau berkebun.', 'icon': '🎵'},
      {'text': 'Akui perasaanmu tanpa menghakimi diri sendiri.', 'icon': '📝'},
      {'text': 'Ambil waktu untuk jalan-jalan di alam untuk menyegarkan pikiran.', 'icon': '🌳'},
      {'text': 'Tuliskan apa yang membuatmu khawatir untuk melepaskannya dari pikiran.', 'icon': '✍️'},
      {'text': 'Kurangi konsumsi kafein yang bisa memperburuk rasa cemas.', 'icon': '☕'},
      {'text': 'Fokus pada apa yang ada di depan mata, satu langkah demi satu langkah.', 'icon': '👣'},
      {'text': 'Pastikan kamu mendapatkan tidur yang berkualitas malam ini.', 'icon': '💤'},
      {'text': 'Jangan ragu untuk menolak permintaan yang memberatkanmu saat ini.', 'icon': '⛔'},
      {'text': 'Ingatkan dirimu bahwa kamu telah melewati masa sulit sebelumnya.', 'icon': '🏅'},
      {'text': 'Jadilah pengamat atas pikiranmu, jangan hanyut di dalamnya.', 'icon': '🧘'},
      {'text': 'Gunakan afirmasi positif untuk menenangkan hatimu yang gelisah.', 'icon': '🗣️'},
      {'text': 'Berikan jarak antara dirimu dan sumber stresmu.', 'icon': '📏'},
      {'text': 'Ciptakan rutinitas pagi yang tenang untuk memulai hari dengan baik.', 'icon': '🌅'},
      {'text': 'Hargai upaya kecilmu dalam menjaga kesehatan mental.', 'icon': '🎖️'},
      {'text': 'Kamu berhak untuk merasa tidak baik-baik saja sesekali.', 'icon': '🫂'},
      {'text': 'Fokus pada pernapasan perut untuk menurunkan tingkat stres.', 'icon': '🔋'},
      {'text': 'Carilah hiburan ringan yang bisa membuatmu tersenyum sejenak.', 'icon': '🧸'},
      {'text': 'Jangan bandingkan bebanmu dengan beban orang lain.', 'icon': '⚖️'},
      {'text': 'Segerakan untuk menyelesaikan tugas yang paling membuatmu terbebani.', 'icon': '✅'},
      {'text': 'Mintalah dukungan dari keluarga atau kerabat dekat.', 'icon': '🏠'},
      {'text': 'Ingatlah bahwa awan mendung pasti akan berlalu.', 'icon': '⛅'},
      {'text': 'Jadilah pelindung bagi ketenangan batinmu sendiri.', 'icon': '🛡️'},
      {'text': 'Berikan dirimu hadiah kecil sebagai bentuk apresiasi diri.', 'icon': '🎁'},
      {'text': 'Fokuslah pada apa yang benar-benar penting untuk kelangsungan hidupmu.', 'icon': '🆘'},
      {'text': 'Gunakan aroma terapi atau mandi air hangat untuk relaksasi.', 'icon': '🛀'},
      {'text': 'Kurangi ekspektasimu terhadap diri sendiri untuk hari ini.', 'icon': '📉'},
      {'text': 'Ingatlah untuk selalu bersikap baik pada diri sendiri.', 'icon': '🧸'},
      {'text': 'Cari tahu apa yang sebenarnya menjadi pemicu rasa waspadamu.', 'icon': '🕵️'},
      {'text': 'Berikan dirimu izin untuk melakukan kesalahan.', 'icon': '🚫'},
      {'text': 'Fokus pada proses, bukan hanya pada hasil akhir yang menakutkan.', 'icon': '🔄'},
      {'text': 'Gunakan seni atau jurnal untuk mengekspresikan perasaanmu.', 'icon': '🎨'},
      {'text': 'Hargai setiap detik ketenangan yang berhasil kamu ciptakan.', 'icon': '⏱️'},
      {'text': 'Jangan biarkan rasa waspada berubah menjadi kepanikan.', 'icon': '🧘'},
      {'text': 'Percayalah bahwa kamu memiliki kekuatan untuk pulih.', 'icon': '🔋'},
      {'text': 'Mintalah pelukan atau dukungan emosional dari orang tercinta.', 'icon': '🫂'},
      {'text': 'Fokuslah pada fakta, bukan pada asumsi yang menakutkan.', 'icon': '📊'},
      {'text': 'Berikan dirimu waktu untuk benar-benar tidak melakukan apa pun.', 'icon': '⏸️'},
      {'text': 'Ingatlah bahwa kamu adalah kapten dari kapal kehidupanmu.', 'icon': '🚢'},
      {'text': 'Jadilah sabar terhadap proses penyembuhan mentalmu.', 'icon': '⏳'},
      {'text': 'Ciptakan ruang aman di rumahmu untuk beristirahat.', 'icon': '🏘️'},
      {'text': 'Teruslah bernapas, kamu sedang melakukan yang terbaik.', 'icon': '🌬️'},
    ],
    'Bahaya': [
      {'text': 'Keamanan dan kesehatanmu adalah prioritas utama. Jangan ragu untuk mencari bantuan profesional.', 'icon': '🆘'},
      {'text': 'Kamu tidak harus menghadapi ini sendirian. Ada banyak tangan yang siap membantumu.', 'icon': '🤝'},
      {'text': 'Ambil langkah mundur dari situasi yang menekan. Berikan dirimu ruang untuk bernapas.', 'icon': '🚪'},
      {'text': 'Setiap badai pasti berlalu. Fokuslah untuk bertahan melewati satu jam ke depan.', 'icon': '⛈️'},
      {'text': 'Sayangi dirimu seperti kamu menyayangi orang yang paling kamu cintai di dunia ini.', 'icon': '🩹'},
      {'text': 'Suaramu penting. Ceritakan bebanmu pada mereka yang bisa memberikan dukungan nyata.', 'icon': '📢'},
      {'text': 'Ingatlah bahwa perasaan ini bersifat sementara, meski terasa sangat berat sekarang.', 'icon': '⏳'},
      {'text': 'Fokuslah pada kebutuhan dasarmu: tidur, makan, dan keamanan lingkungan.', 'icon': '🛌'},
      {'text': 'Kamu berharga dan keberadaanmu sangat berarti bagi banyak orang.', 'icon': '💎'},
      {'text': 'Tarik napas dalam, kamu telah melalui banyak hal sulit sebelumnya dan kamu akan melaluinya lagi.', 'icon': '🌈'},
      {'text': 'Jangkau layanan darurat atau hotline kesehatan mental jika diperlukan.', 'icon': '📞'},
      {'text': 'Matikan semua pemicu stres dan fokus hanya pada keamananmu.', 'icon': '📴'},
      {'text': 'Biarkan orang lain membantumu membawakan bebanmu hari ini.', 'icon': '🤲'},
      {'text': 'Ingatkan dirimu bahwa kamu memiliki nilai yang tak terhingga.', 'icon': '✨'},
      {'text': 'Berikan dirimu kasih sayang yang tak terbatas saat ini.', 'icon': '💗'},
      {'text': 'Fokuslah pada pernapasanmu sebagai jangkar kehidupan.', 'icon': '⚓'},
      {'text': 'Kamu adalah pejuang yang sangat tangguh, istirahatlah sejenak.', 'icon': '🛡️'},
      {'text': 'Cari tempat yang paling tenang dan aman untukmu saat ini.', 'icon': '🛖'},
      {'text': 'Jangan buat keputusan permanen untuk masalah yang bersifat sementara.', 'icon': '⏳'},
      {'text': 'Ada harapan di ujung jalan ini, percayalah meski tak terlihat.', 'icon': '🔦'},
      {'text': 'Kehadiranmu di dunia ini adalah sebuah anugerah.', 'icon': '🌍'},
      {'text': 'Bicaralah dengan suara lembut pada dirimu sendiri.', 'icon': '🤫'},
      {'text': 'Ambil satu langkah kecil saja untuk membuatmu merasa lebih aman.', 'icon': '👣'},
      {'text': 'Ingatlah orang-orang yang peduli dan menyayangimu.', 'icon': '👨‍👩‍👧‍👦'},
      {'text': 'Kamu berhak untuk mendapatkan bantuan dan dukungan.', 'icon': '🆘'},
      {'text': 'Fokuslah pada apa yang bisa kamu sentuh, dengar, dan lihat saat ini.', 'icon': '🖐️'},
      {'text': 'Biarkan emosimu keluar melalui cara yang aman.', 'icon': '🌊'},
      {'text': 'Ingatkan dirimu bahwa kamu tidak sendirian di dunia ini.', 'icon': '👫'},
      {'text': 'Berikan dirimu izin untuk benar-benar berhenti sejenak.', 'icon': '🛑'},
      {'text': 'Keberanianmu untuk bertahan hari ini adalah kemenangan besar.', 'icon': '🚩'},
      {'text': 'Fokuslah pada kenyamanan fisik yang bisa kamu dapatkan.', 'icon': '🧣'},
      {'text': 'Percayalah bahwa bantuan akan datang tepat pada waktunya.', 'icon': '⌛'},
      {'text': 'Kamu adalah bagian penting dari alam semesta ini.', 'icon': '🌌'},
      {'text': 'Biarkan dirimu menangis sepuasnya jika itu melegakan.', 'icon': '💧'},
      {'text': 'Ingatlah bahwa setiap hari baru membawa peluang untuk sembuh.', 'icon': '🌅'},
      {'text': 'Fokuslah pada hal terkecil yang bisa kamu syukuri saat ini.', 'icon': '🔍'},
      {'text': 'Jadilah sangat lembut dan penuh kasih pada jiwamu yang lelah.', 'icon': '🦢'},
      {'text': 'Kamu lebih kuat dari rasa sakit yang kamu rasakan.', 'icon': '🏋️'},
      {'text': 'Bicaralah pada seseorang yang benar-benar memahamimu.', 'icon': '👂'},
      {'text': 'Berikan dirimu ruang untuk benar-benar pulih sepenuhnya.', 'icon': '🛌'},
      {'text': 'Ingatkan dirimu bahwa kamu layak untuk hidup bahagia.', 'icon': '🌻'},
      {'text': 'Fokuslah pada detak jantungmu, tanda bahwa kehidupan terus berlanjut.', 'icon': '💓'},
      {'text': 'Kamu adalah permata yang sedang diproses menjadi lebih indah.', 'icon': '💎'},
      {'text': 'Jangan menyerah, cahaya akan segera menyapa harimu.', 'icon': '☀️'},
      {'text': 'Mintalah pertolongan profesional tanpa rasa malu.', 'icon': '🏥'},
      {'text': 'Ingatkan dirimu tentang alasan-alasan kecil untuk terus bertahan.', 'icon': '📌'},
      {'text': 'Kamu adalah pahlawan bagi dirimu sendiri hari ini.', 'icon': '🦸'},
      {'text': 'Fokuslah pada ketenangan batin yang bisa kamu temukan.', 'icon': '🕊️'},
      {'text': 'Percayalah pada kekuatan penyembuhan waktu dan cinta.', 'icon': '🕰️'},
      {'text': 'Tetaplah bersama kami, duniamu masih menantikan sinarmu.', 'icon': '🌟'},
    ],
  };

  static String getRandomQuote(String mood) {
    final quotes = moodQuotes[mood.toLowerCase()] ?? moodQuotes['biasa']!;
    return quotes[Random().nextInt(quotes.length)];
  }

  static List<Map<String, dynamic>> getRandomInspirations(String category, int count) {
    final inspirations = dailyInspirations[category] ?? dailyInspirations['Stabil']!;
    final List<Map<String, dynamic>> result = List.from(inspirations);
    result.shuffle();
    return result.take(count).toList();
  }
}
